default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  username: rails_cushion
  password:

development:
  <<: *default
  database: rails_cushion_development

test:
  <<: *default
  database: rails_cushion_test

production:
  <<: *default
  database: rails_cushion_production
  password: <%= ENV['RAILS_CUSHION_DATABASE_PASSWORD'] %>
